cursor            {{ colors.primary.dark.hex }}
cursor_text_color {{ colors.on_primary.dark.hex }}

foreground {{ colors.on_surface_variant.dark.hex }}
background            {{ colors.surface_container_lowest.dark.hex }}
selection_foreground  {{ colors.on_secondary.dark.hex }}
selection_background  {{ colors.secondary.dark.hex }}
url_color             {{ colors.secondary.dark.hex }}

# black / gray
color0  {{ colors.surface_container_lowest.dark.hex }}
color8  {{ colors.surface_container_high.dark.hex }}

# red
color1  {{ colors.error.dark.hex }}
color9  {{ colors.error_container.dark.hex }}

# green (use primary instead of weird fixed)
color2  {{ colors.primary.dark.hex }}
color10 {{ colors.primary_container.dark.hex }}

# yellow (tertiary but stronger)
color3  {{ colors.tertiary.dark.hex }}
color11 {{ colors.tertiary_container.dark.hex }}

# blue (keep primary variant for clarity)
color4  {{ colors.primary_fixed.dark.hex }}
color12 {{ colors.primary_fixed.dark.hex }}

# magenta (secondary works better here)
color5  {{ colors.secondary.dark.hex }}
color13 {{ colors.secondary_container.dark.hex }}

# cyan (use tertiary variant)
color6  {{ colors.tertiary.dark.hex }}
color14 {{ colors.tertiary_fixed.dark.hex }}

# white
color7  {{ colors.on_surface.dark.hex }}
color15 {{ colors.on_surface_variant.dark.hex }}

mark1_foreground {{ colors.on_primary_fixed.dark.hex }}
mark1_background {{ colors.primary_fixed.dark.hex }}
mark2_foreground {{ colors.on_secondary_fixed.dark.hex }}
mark2_background {{ colors.secondary_fixed.dark.hex }}
mark3_foreground {{ colors.on_tertiary_fixed.dark.hex }}
mark3_background {{ colors.tertiary_fixed.dark.hex }}

active_tab_foreground {{ colors.on_primary.dark.hex }}
active_tab_background {{ colors.primary.dark.hex }}
inactive_tab_foreground {{ colors.on_primary_container.dark.hex }}
inactive_tab_background {{ colors.primary_container.dark.hex }}

active_border_color {{ colors.primary.dark.hex }}
inactive_border_color {{ colors.on_primary.dark.hex }}
# bell_border_color #ff5a00
