$image = /home/yugg755/Pictures/Wallpapers/wp-rice.png

$background = rgba(151313ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(332f30ff)

$inverse_primary = rgba(6e595fff)

$inverse_surface = rgba(e8e1e1ff)

$on_background = rgba(e8e1e1ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(3e2b31ff)

$on_primary_container = rgba(f8dbe3ff)

$on_primary_fixed = rgba(27171dff)

$on_primary_fixed_variant = rgba(554148ff)

$on_secondary = rgba(392d31ff)

$on_secondary_container = rgba(f2dde2ff)

$on_secondary_fixed = rgba(23191cff)

$on_secondary_fixed_variant = rgba(514347ff)

$on_surface = rgba(e8e1e1ff)

$on_surface_variant = rgba(ccc5c5ff)

$on_tertiary = rgba(422932ff)

$on_tertiary_container = rgba(ffd9e4ff)

$on_tertiary_fixed = rgba(2a151dff)

$on_tertiary_fixed_variant = rgba(5a3f48ff)

$outline = rgba(958f90ff)

$outline_variant = rgba(4a4646ff)

$primary = rgba(dbbfc7ff)

$primary_container = rgba(554148ff)

$primary_fixed = rgba(f8dbe3ff)

$primary_fixed_dim = rgba(dbbfc7ff)

$scrim = rgba(000000ff)

$secondary = rgba(d5c2c6ff)

$secondary_container = rgba(514347ff)

$secondary_fixed = rgba(f2dde2ff)

$secondary_fixed_dim = rgba(d5c2c6ff)

$shadow = rgba(000000ff)

$source_color = rgba(56484cff)

$surface = rgba(151313ff)

$surface_bright = rgba(3c3839ff)

$surface_container = rgba(221f1fff)

$surface_container_high = rgba(2c292aff)

$surface_container_highest = rgba(373434ff)

$surface_container_low = rgba(1e1b1bff)

$surface_container_lowest = rgba(100e0eff)

$surface_dim = rgba(151313ff)

$surface_tint = rgba(dbbfc7ff)

$surface_variant = rgba(4a4646ff)

$tertiary = rgba(e2bdc8ff)

$tertiary_container = rgba(5a3f48ff)

$tertiary_fixed = rgba(ffd9e4ff)

$tertiary_fixed_dim = rgba(e2bdc8ff)

