cursor            #bccaba
cursor_text_color #273328

foreground #c7c6c4
background            #0d0e0d
selection_foreground  #2b322b
selection_background  #c1c9be
url_color             #c1c9be

# black / gray
color0  #0d0e0d
color8  #292a28

# red
color1  #ffb4ab
color9  #93000a

# green (use primary instead of weird fixed)
color2  #bccaba
color10 #3d4a3e

# yellow (tertiary but stronger)
color3  #b7ccb7
color11 #394b3b

# blue (keep primary variant for clarity)
color4  #d8e6d6
color12 #d8e6d6

# magenta (secondary works better here)
color5  #c1c9be
color13 #414941

# cyan (use tertiary variant)
color6  #b7ccb7
color14 #d3e8d2

# white
color7  #e4e2df
color15 #c7c6c4

mark1_foreground #131e14
mark1_background #d8e6d6
mark2_foreground #161d17
mark2_background #dde5da
mark3_foreground #0e1f12
mark3_background #d3e8d2

active_tab_foreground #273328
active_tab_background #bccaba
inactive_tab_foreground #d8e6d6
inactive_tab_background #3d4a3e

active_border_color #bccaba
inactive_border_color #273328
# bell_border_color #ff5a00
