cursor            #dec0b2
cursor_text_color #3f2c22

foreground #ccc5c2
background            #100e0c
selection_foreground  #3b2e27
selection_background  #d7c2b9
url_color             #d7c2b9

# black / gray
color0  #100e0c
color8  #2d2928

# red
color1  #ffb4ab
color9  #93000a

# green (use primary instead of weird fixed)
color2  #dec0b2
color10 #574237

# yellow (tertiary but stronger)
color3  #e6beab
color11 #5c4132

# blue (keep primary variant for clarity)
color4  #fcdccd
color12 #fcdccd

# magenta (secondary works better here)
color5  #d7c2b9
color13 #52443c

# cyan (use tertiary variant)
color6  #e6beab
color14 #ffdbca

# white
color7  #e9e1de
color15 #ccc5c2

mark1_foreground #28180f
mark1_background #fcdccd
mark2_foreground #241913
mark2_background #f4ded4
mark3_foreground #2b160a
mark3_background #ffdbca

active_tab_foreground #3f2c22
active_tab_background #dec0b2
inactive_tab_foreground #fcdccd
inactive_tab_background #574237

active_border_color #dec0b2
inactive_border_color #3f2c22
# bell_border_color #ff5a00
