cursor            #cfc2d3
cursor_text_color #352d3b

foreground #cac5c7
background            #0f0e0f
selection_foreground  #342e37
selection_background  #cdc3ce
url_color             #cdc3ce

# black / gray
color0  #0f0e0f
color8  #2b292b

# red
color1  #ffb4ab
color9  #93000a

# green (use primary instead of weird fixed)
color2  #cfc2d3
color10 #4c4452

# yellow (tertiary but stronger)
color3  #d1c1d9
color11 #4e4256

# blue (keep primary variant for clarity)
color4  #ecdef0
color12 #ecdef0

# magenta (secondary works better here)
color5  #cdc3ce
color13 #4b454d

# cyan (use tertiary variant)
color6  #d1c1d9
color14 #eeddf5

# white
color7  #e6e1e3
color15 #cac5c7

mark1_foreground #201925
mark1_background #ecdef0
mark2_foreground #1f1a21
mark2_background #e9dfea
mark3_foreground #221829
mark3_background #eeddf5

active_tab_foreground #352d3b
active_tab_background #cfc2d3
inactive_tab_foreground #ecdef0
inactive_tab_background #4c4452

active_border_color #cfc2d3
inactive_border_color #352d3b
# bell_border_color #ff5a00
