linux_display_server wayland
# wayland_titlebar_color background

font_size 11
background_opacity 0.85
# window settings
initial_window_width 95c
initial_window_height 35c
allow_remote_control yes
window_padding_width 4
confirm_os_window_close 0
placement_strategy center
# cursor #e4e1e9
# cursor_text_color #c7c5d0

# Keybindings
map kitty_mod+t     new_tab_with_cwd

scrollback_lines 100000



# Font
font_family      JetBrainsMono Nerd Font

# Better readable ANSI colors (override Matugen)

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
